name: "run-verzon"
description: "The only release tool you’ll ever need. Built in Rust for speed and reliability."
author: "Simon Kovtyk"
runs:
  using: "composite"
  steps:
    - shell: bash
      id: checksum
      run: |
        curl -L -o verzon-sha256 https://github.com/verzon-ci/verzon/releases/download/latest/verzon-x86_64-unknown-linux-gnu.sha256
        echo "verzon-sha256=$(cat verzon-sha256)" >> $GITHUB_OUTPUT"

    - uses: actions/cache@v5
      id: cache
      with:
        path: ~/.verzon
        key: ${{ runner.os }}-verzon-${{ steps.checksum.outputs.verzon-sha256 }}

    - shell: bash
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: |
        curl -L -o verzon-bin https://github.com/verzon-ci/verzon/releases/download/latest/verzon-x86_64-unknown-linux-gnu
        mv verzon-bin ~/.local/bin/verzon
        echo "~/.local/bin" >> "$GITHUB_PATH"

    - uses: actions/checkout@v6

    - shell: bash
      run: |
        verzon --help
